name: nsfw_util
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4
  tflite_flutter: ^0.12.1
  video_compress: ^3.1.4
  video_snapshot_generator: ^0.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/models/
